-- Salamandra IoT - Supabase PostgreSQL schema completo
-- Ejecutar en Supabase SQL Editor. Requiere Authentication habilitado por Email.

create extension if not exists "pgcrypto";

-- ENUMS
create type app_role as enum ('superadmin','administrador','emprendedor','business');
create type user_status as enum ('activo','pendiente','bloqueado');
create type subscription_status as enum ('activa','prueba','vencida','cancelada');
create type ticket_status as enum ('abierto','en_proceso','cerrado');
create type ticket_priority as enum ('baja','media','alta','urgente');
create type device_status as enum ('online','offline','mantenimiento');

-- PERFILES Y ROLES
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text unique,
  avatar_url text,
  role app_role not null default 'emprendedor',
  status user_status not null default 'pendiente',
  phone text,
  company text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permissions (
  id bigserial primary key,
  role app_role not null,
  module text not null,
  can_view boolean not null default true,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  unique(role,module)
);

-- PLANES Y SUSCRIPCIONES
create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  max_devices int not null default 1,
  monthly_usd numeric(10,2) not null default 9.99,
  annual_usd numeric(10,2) not null default 99.99,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete cascade,
  plan_id uuid references public.plans(id),
  status subscription_status not null default 'prueba',
  amount_usd numeric(10,2) not null default 0,
  started_at timestamptz not null default now(),
  expires_at timestamptz
);

-- UBICACIONES, DISPOSITIVOS, SENSORES, ACTUADORES
create table if not exists public.places (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  address text,
  lat numeric(10,7),
  lng numeric(10,7),
  created_at timestamptz not null default now()
);

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  place_id uuid references public.places(id) on delete cascade,
  owner_id uuid references public.profiles(id) on delete set null,
  name text not null,
  device_code text not null unique, -- ESPXXXX
  serial_number text not null unique, -- EG + últimos 6 MAC
  mac text,
  category text default 'generico',
  address text,
  status device_status not null default 'offline',
  wifi_rssi int,
  broker_connected boolean not null default false,
  last_reset_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_types (
  id bigserial primary key,
  name text not null unique,
  icon text default 'generic',
  unit text,
  config jsonb not null default '{}'::jsonb
);

create table if not exists public.sensors (
  id uuid primary key default gen_random_uuid(),
  device_id uuid references public.devices(id) on delete cascade,
  sensor_type_id bigint references public.sensor_types(id),
  name text not null,
  gpio text,
  esp32_variable text,
  icon text default 'generic',
  unit text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  sensor_id uuid references public.sensors(id) on delete cascade,
  device_id uuid references public.devices(id) on delete cascade,
  variable text not null,
  value numeric(12,4) not null,
  unit text,
  recorded_at timestamptz not null default now()
);
create index if not exists idx_sensor_readings_sensor_time on public.sensor_readings(sensor_id, recorded_at desc);
create index if not exists idx_sensor_readings_device_time on public.sensor_readings(device_id, recorded_at desc);

create table if not exists public.actuators (
  id uuid primary key default gen_random_uuid(),
  device_id uuid references public.devices(id) on delete cascade,
  name text not null,
  gpio text,
  esp32_variable text,
  icon text default 'plug',
  state boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.actuator_events (
  id bigint generated by default as identity primary key,
  actuator_id uuid references public.actuators(id) on delete cascade,
  state boolean not null,
  source text default 'pwa',
  profile_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- BROKER MQTT / CONFIGURACIÓN
create table if not exists public.mqtt_brokers (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Broker Salamandra',
  host text not null,
  port int not null default 1883,
  username text,
  password_secret text,
  status text default 'offline',
  latency_ms int,
  updated_at timestamptz not null default now()
);

create table if not exists public.software_settings (
  id int primary key default 1,
  logo_light text,
  logo_dark text,
  favicon text,
  install_icon text,
  footer_href text default 'https://electronicagambino.com',
  updated_at timestamptz not null default now(),
  constraint single_settings_row check (id=1)
);

-- SOPORTE E INVENTARIO
create table if not exists public.support_tickets (
  id bigserial primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  subject text not null,
  message text,
  status ticket_status not null default 'abierto',
  priority ticket_priority not null default 'media',
  assigned_to uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sku text unique,
  category text,
  stock int not null default 0,
  min_stock int not null default 0,
  unit_cost_usd numeric(10,2) default 0,
  location text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- TRIGGERS
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name,role,status)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''), 'emprendedor','activo')
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

-- DATA INICIAL
insert into public.sensor_types(name,icon,unit,config) values
('DHT11','temperature','°C/%','{"series":["temperatura","humedad"]}'),
('DHT22 (Temp+Hum)','temperature','°C/%','{"series":["temperatura","humedad"]}'),
('MQ135','gas','ppm','{"series":["co2","metano","butano","propano"]}'),
('Hum Suelo','soil','%','{}'),
('pH','ph','pH','{}'),
('Conductividad (EC)','electric','µS/cm','{}'),
('Nivel','humidity','%','{}')
on conflict (name) do nothing;

insert into public.plans(name,description,max_devices,monthly_usd,annual_usd) values
('Plan Emprendedor','Solo un dispositivo SalamandraIoT basado en ESP32',1,9.99,99.99),
('Plan Business','Hasta 5 dispositivos SalamandraIoT basados en ESP32',5,29.99,299.99)
on conflict do nothing;

insert into public.permissions(role,module,can_view,can_create,can_edit,can_delete) values
('superadmin','dashboard',true,true,true,true),('superadmin','usuarios',true,true,true,true),('superadmin','roles',true,true,true,true),('superadmin','planes',true,true,true,true),('superadmin','dispositivos',true,true,true,true),('superadmin','soporte',true,true,true,true),('superadmin','inventario',true,true,true,true),
('administrador','dashboard',true,false,true,false),('administrador','dispositivos',true,true,true,false),('administrador','soporte',true,true,true,false),
('emprendedor','dashboard',true,false,false,false),('emprendedor','dispositivos',true,false,false,false),('emprendedor','soporte',true,true,false,false),
('business','dashboard',true,false,true,false),('business','dispositivos',true,true,true,false),('business','soporte',true,true,true,false)
on conflict(role,module) do nothing;

-- RLS
alter table public.profiles enable row level security;
alter table public.permissions enable row level security;
alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.places enable row level security;
alter table public.devices enable row level security;
alter table public.sensors enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.actuators enable row level security;
alter table public.actuator_events enable row level security;
alter table public.support_tickets enable row level security;
alter table public.inventory_items enable row level security;
alter table public.mqtt_brokers enable row level security;
alter table public.software_settings enable row level security;

create or replace function public.is_superadmin()
returns boolean language sql stable security definer as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='superadmin' and status='activo');
$$;

-- Políticas simples para desarrollo seguro
create policy "profiles_self_read" on public.profiles for select using (id=auth.uid() or public.is_superadmin());
create policy "profiles_superadmin_all" on public.profiles for all using (public.is_superadmin()) with check (public.is_superadmin());
create policy "plans_read_all" on public.plans for select using (true);
create policy "superadmin_all_plans" on public.plans for all using (public.is_superadmin()) with check (public.is_superadmin());
create policy "superadmin_all_support" on public.support_tickets for all using (public.is_superadmin()) with check (public.is_superadmin());
create policy "support_own" on public.support_tickets for select using (profile_id=auth.uid());
create policy "support_insert_own" on public.support_tickets for insert with check (profile_id=auth.uid());
create policy "superadmin_inventory" on public.inventory_items for all using (public.is_superadmin()) with check (public.is_superadmin());

-- Para las tablas operativas, durante desarrollo se permite al usuario autenticado leer/escribir sus datos y al SuperAdmin todo.
create policy "auth_places" on public.places for all using (profile_id=auth.uid() or public.is_superadmin()) with check (profile_id=auth.uid() or public.is_superadmin());
create policy "auth_devices" on public.devices for all using (owner_id=auth.uid() or public.is_superadmin()) with check (owner_id=auth.uid() or public.is_superadmin());
create policy "auth_sensors" on public.sensors for all using (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid())) with check (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid()));
create policy "auth_sensor_readings" on public.sensor_readings for all using (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid())) with check (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid()));
create policy "auth_actuators" on public.actuators for all using (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid())) with check (public.is_superadmin() or exists(select 1 from public.devices d where d.id=device_id and d.owner_id=auth.uid()));
create policy "auth_actuator_events" on public.actuator_events for all using (public.is_superadmin() or profile_id=auth.uid()) with check (public.is_superadmin() or profile_id=auth.uid());

-- Vistas útiles para dashboard SuperAdmin
create or replace view public.v_superadmin_dashboard as
select
  (select count(*) from public.profiles) as users_count,
  (select count(*) from public.subscriptions where status in ('activa','prueba')) as subscribers_count,
  (select coalesce(sum(amount_usd),0) from public.subscriptions where status='activa') as income_usd,
  (select count(*) from public.devices where status='online') as devices_online,
  (select count(*) from public.support_tickets where status <> 'cerrado') as open_tickets,
  (select count(*) from public.inventory_items where stock <= min_stock) as low_stock_items;
